Ext.define('Project1.project1.shared.com.model.testproj1boundedcontext.proj.ItemModel', {
     "extend": "Ext.data.Model",
     "fields": [{
          "name": "primaryKey",
          "type": "auto",
          "defaultValue": ""
     }, {
          "name": "itemid",
          "type": "int",
          "defaultValue": ""
     }, {
          "name": "itemname",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "price",
          "type": "int",
          "defaultValue": ""
     }, {
          "name": "itemicon",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "quantity",
          "type": "int",
          "defaultValue": ""
     }, {
          "name": "itemsize",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "itemorderdate",
          "type": "auto",
          "defaultValue": ""
     }, {
          "name": "homedelivery",
          "type": "boolean",
          "defaultValue": ""
     }, {
          "name": "total",
          "type": "int",
          "defaultValue": ""
     }, {
          "name": "versionId",
          "type": "int",
          "defaultValue": ""
     }, {
          "name": "entityAudit",
          "reference": "EntityAudit"
     }, {
          "name": "primaryDisplay",
          "type": "string",
          "defaultValue": ""
     }]
});