Ext.define('Project1.project1.web.com.view.organization.contactmanagement.NewFormPanel', {
     "xtype": "newFormPanel",
     "items": [{
          "xtype": "textfield",
          "fieldLabel": "TextField",
          "margin": 5,
          "bindable": "nametetet",
          "name": "nametetet",
          "itemId": "textfield_ext_6664"
     }, {
          "xtype": "numberfield",
          "fieldLabel": "itemid",
          "name": "itemid",
          "margin": 5,
          "bindable": "itemid",
          "text": "itemid",
          "fieldName": "itemid",
          "displayName": "itemid",
          "widget": "numberfield",
          "isField": true,
          "itemId": "numberfield_ext_6706"
     }, {
          "xtype": "textfield",
          "fieldLabel": "itemName",
          "margin": 5,
          "bindable": "itemname",
          "name": "itemname",
          "text": "itemName",
          "fieldName": "itemname",
          "displayName": "itemName",
          "widget": "textfield",
          "min": "1",
          "max": "255",
          "isField": true,
          "itemId": "textfield_ext_6717"
     }, {
          "xtype": "numberfield",
          "fieldLabel": "itemPrice",
          "name": "price",
          "margin": 5,
          "bindable": "price",
          "text": "itemPrice",
          "fieldName": "price",
          "displayName": "itemPrice",
          "widget": "numberfield",
          "min": "-9223372000000000000",
          "max": "9223372000000000000",
          "isField": true,
          "itemId": "numberfield_ext_6730"
     }, {
          "xtype": "numberfield",
          "fieldLabel": "itemQuantity",
          "name": "quantity",
          "margin": 5,
          "bindable": "quantity",
          "text": "itemQuantity",
          "fieldName": "quantity",
          "displayName": "itemQuantity",
          "widget": "numberfield",
          "min": "-2147483648",
          "max": "2147483647",
          "isField": true,
          "itemId": "numberfield_ext_6763"
     }, {
          "xtype": "textfield",
          "fieldLabel": "itemSize",
          "margin": 5,
          "bindable": "itemsize",
          "name": "itemsize",
          "text": "itemSize",
          "fieldName": "itemsize",
          "displayName": "itemSize",
          "widget": "textfield",
          "min": "1",
          "max": "4",
          "isField": true,
          "itemId": "textfield_ext_6783"
     }, {
          "xtype": "combo",
          "name": "newtesting",
          "margin": 5,
          "bindable": "newtesting",
          "typeAhead": true,
          "queryMode": "local",
          "minChars": 1,
          "fieldLabel": "ComboBox",
          "displayField": "countryId",
          "valueField": "countryName",
          "itemId": "combo_ext_6869",
          "store": {
               "model": "Project1.project1.shared.com.model.organization.locationmanagement.CountryModel",
               "autoLoad": true,
               "autoSync": true,
               "sorters": [{
                    "property": "countryId",
                    "direction": "ASC"
               }],
               "proxy": {
                    "type": "ajax",
                    "url": "secure/Country/findAll",
                    "serviceId": "2994D13E-2083-4910-BC2C-C2C26CE9107A",
                    "serviceOperationId": "93AA016D-668F-4AA2-84B4-6795F1586732",
                    "serviceType": 1,
                    "actionMethods": {
                         "read": "GET"
                    },
                    "headers": {
                         "Content-Type": "application/json"
                    },
                    "extraParams": {},
                    "reader": {
                         "type": "json",
                         "rootProperty": "response.data"
                    }
               }
          }
     }],
     "margin": 5,
     "border": true,
     "autoScroll": true,
     "title": "Panel",
     "dockedItems": [],
     "itemId": "panel_ext_6653",
     "extend": "Ext.panel.Panel",
     "requires": ["Project1.project1.shared.com.model.organization.locationmanagement.CountryModel", "Project1.project1.web.com.controller.organization.contactmanagement.NewFormPanelController", "Project1.project1.shared.com.viewmodel.organization.contactmanagement.NewFormPanelViewModel", "Project1.project1.shared.com.model.organization.contactmanagement.NewFormPanelModel"],
     "viewModel": "NewFormPanelViewModel",
     "controller": "NewFormPanelController"
});