Ext.define('Project1.project1.shared.com.model.organization.contactmanagement.NewFormPanelModel', {
     "extend": "Ext.data.Model",
     "fields": [{
          "name": "nametetet",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "itemid",
          "type": "int",
          "defaultValue": ""
     }, {
          "name": "itemname",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "price",
          "type": "int",
          "defaultValue": ""
     }, {
          "name": "quantity",
          "type": "int",
          "defaultValue": ""
     }, {
          "name": "itemsize",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "newtesting",
          "type": "string",
          "defaultValue": ""
     }]
});